### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by plingampally** [elsehow/moneybot#32]
I'm just trying to get the backtest example working so I didn't bother updating the `config-example.yml` with my Poloniex keys.  

InfluxDB is running, and I used this command to populate it with historical data: 
`DB_RELEASE=7-5-2017 DB_NAME=historical-poloniex INFLUX_DIR=/usr/local/var/influxdb ./local-services/influxdb/restore.sh`

After trying to run the backtest like this: 
`python3 examples/backtest.py -c config-example.yml -s buffed-coin` 

I receive the following error log: 

```
INFO:staticconf.config:Unexpected value in moneybot configuration: [('influxdb.host', 'localhost'), ('influxdb.port', 8086), ('influxdb.username', 'root'), ('influxdb.password', 'root'), ('influxdb.database', 'historical-poloniex'), ('poloniex.key', 'YOUR_API_KEY'), ('poloniex.secret', 'YOUR_API_SECRET'), ('trading.fiat', 'BTC'), ('trading.interval', 86400)]
INFO:moneybot.evaluate:Testing from 2017-01-01 00:00:00 to 2017-01-15 00:00:00
INFO:moneybot.evaluate:Testing from 2017-01-15 00:00:00 to 2017-01-29 00:00:00
INFO:moneybot.evaluate:Testing from 2017-01-29 00:00:00 to 2017-02-12 00:00:00
INFO:moneybot.evaluate:Testing from 2017-02-12 00:00:00 to 2017-02-26 00:00:00
INFO:moneybot.evaluate:Testing from 2017-02-26 00:00:00 to 2017-03-12 00:00:00
INFO:moneybot.evaluate:Testing from 2017-03-12 00:00:00 to 2017-03-26 00:00:00
INFO:moneybot.evaluate:Testing from 2017-03-26 00:00:00 to 2017-04-09 00:00:00
INFO:moneybot.evaluate:Testing from 2017-04-09 00:00:00 to 2017-04-23 00:00:00
INFO:moneybot.evaluate:Testing from 2017-04-23 00:00:00 to 2017-05-07 00:00:00
INFO:moneybot.evaluate:Testing from 2017-05-07 00:00:00 to 2017-05-21 00:00:00
INFO:moneybot.evaluate:Testing from 2017-05-21 00:00:00 to 2017-06-04 00:00:00
INFO:moneybot.evaluate:Testing from 2017-06-04 00:00:00 to 2017-06-18 00:00:00
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/plingampally/dev/moneybot/moneybot/evaluate.py", line 65, in backtest
    return list(fund.begin_backtest(start, end))
  File "/Users/plingampally/dev/moneybot/moneybot/fund.py", line 112, in begin_backtest
    val = self.step(date)
  File "/Users/plingampally/dev/moneybot/moneybot/fund.py", line 44, in step
    market_state = self.market_adapter.get_market_state(time)
  File "/Users/plingampally/dev/moneybot/moneybot/market/adapters/__init__.py", line 45, in get_market_state
    charts = self.market_history.latest(time)
  File "/Users/plingampally/dev/moneybot/moneybot/market/history.py", line 173, in latest
    result_set = self.client.query(q)
  File "/Users/plingampally/dev/moneybot/venv/lib/python3.6/site-packages/influxdb/client.py", line 392, in query
    in data.get('results', [])
  File "/Users/plingampally/dev/moneybot/venv/lib/python3.6/site-packages/influxdb/client.py", line 391, in <listcomp>
    for result
  File "/Users/plingampally/dev/moneybot/venv/lib/python3.6/site-packages/influxdb/resultset.py", line 23, in __init__
    raise InfluxDBClientError(self.error)
influxdb.exceptions.InfluxDBClientError: database not found: historical-poloniex
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/backtest.py", line 73, in <module>
    main(args)
  File "examples/backtest.py", line 43, in main
    window_distance_days=14,
  File "/Users/plingampally/dev/moneybot/moneybot/evaluate.py", line 89, in evaluate
    results = p.map(backtest, time_tuples)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
influxdb.exceptions.InfluxDBClientError: database not found: historical-poloniex
```

**Comment by elsehow** [comment]
@plingampally Thanks for opening this issue. 

For starters, make sure your `influxd` isn't running when you do the restore step. Bug us again if the issue persists.

**Comment by plingampally** [comment]
That was it, thanks!
